name: CI

on:
  push:
    branches:
      - main
      - dev

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Test placeholder
        run: |
          echo "TODO: run tests"
